### ISSUE TITLE
Show matrix with values

### ISSUE THREAD

**Issue by bensuperpc** [rigtorp/c2clat#3]
I would like to display the values ​​in the matrix, but I am not coming up with something clean,

I replace these lines:

```
std::cout << "EOD\n"
  << "plot '$data' matrix rowheaders columnheaders using 2:1:3 "
   "with image,'\n";
```

With:

```
std::cout << "EOD\n"
  << "plot '$data' matrix rowheaders columnheaders using 2:1:3 "
   "with image,'' matrix using 1:2:(sprintf('%d',$3)) with labels font ',auto'\n";
```

Or with

```
    std::cout << "EOD\n"
              << "plot '$data' matrix rowheaders columnheaders using 2:1:3 "
                 "with image,'' matrix using ($1-1):($2-1):(sprintf('%d',$3)) with labels font ',auto'\n";
```

I have this warning:
`        line 18: warning: matrix contains missing or undefined values`

I can't find the right configuration for gnuplot

**Comment by rigtorp** [comment]
```gnuplot
plot '$data' matrix rowheaders columnheaders using 2:1:3 with image, \
     '$data' matrix rowheaders columnheaders using 2:1:(sprintf("%g",$3)) with labels
```

**Comment by bensuperpc** [comment]
> ```gnuplot
> plot '$data' matrix rowheaders columnheaders using 2:1:3 with image, \
>      '$data' matrix rowheaders columnheaders using 2:1:(sprintf("%g",$3)) with labels
> ```

Thanks, it works ^^
